### ISSUE TITLE
19.10 debug-iso #7: "Something has gone wrong." with gnome-control-center user

### ISSUE THREAD

**Issue by brs17** [pop-os/session#11]
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 19.10 debug iso 7
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
gnome-initial-setup (presumably)

**Issue/Bug Description:**
After installing 19.10 iso#7 from a usb, I am presented with the following screen in the gnome-initial-setup user. Virtual terminals are available but I am not aware of how to log in to the gnome-initial-setup user.

![somethingwrong](https://user-images.githubusercontent.com/7460774/65824196-14f6e100-e222-11e9-8537-93c27d695adb.jpg)

**Comment by mmstick** [comment]
So far, no luck. I don't see any critical issues on startup that indicate why the initial setup session is failing to start. Journald logs that the initial setup application has launched and is running in the background, and `gnome-session` in debug mode does not report any issues with its log. GNOME Shell also does not report any errors besides theme error warnings.

- [boot log](https://github.com/pop-os/session/files/3703725/boot.log).
- [gnome-session log](https://github.com/pop-os/session/files/3703982/gnome-session.log).

Things I've tried:

- Removing all shell extensions by moving `/usr/share/gnome-shell/extensions` to another location.
- Removing all default settings for the Pop session, by moving all `/usr/share/glib-2.0/schemas/50-pop*` files.
- Replacing the `gnome-session` binary with a script that invokes `--failsafe` and `--debug &> /tmp/gnome-session.log`
- Setting `XDG_SESSION_TYPE=x11` and `GDK_BACKEND=x11` in the xinitrc

**Comment by mmstick** [comment]
After upgrading the installed system to the latest packages (3.34.1 packages were pulled in), initial setup is working. I'll build a new ISO and try again.

**Comment by mmstick** [comment]
Fixed by new ISO
