### ISSUE TITLE
Emoji picker bound to incorrect keys

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/session#45]
Currently bound to `Ctrl + .` but should be `Ctrl + Shift + .`

`Ctrl + .` conflicts with 1password. Additionally, the current emoji picker doesn't needs improvement. It's unclear what to do once it's accidentally activated. Re-adding the `Shift` will avoid accidental activation.

**Comment by jackpot51** [comment]
Fixed in https://github.com/pop-os/session/commit/0e196e0a7161a8c017ac4b05db6f9b9d22c47c51

**Comment by jackpot51** [comment]
I chose Ctrl+Shift+E because, as Michael says, it matches better with the unicode input.
